//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOutline
    {
        public long COTID { get; set; }
        public Nullable<long> FKCDID { get; set; }
        public Nullable<long> FKCMTID { get; set; }
        public string OName { get; set; }
        public string Olink { get; set; }
        public string ODescription { get; set; }
        public Nullable<bool> IsRecStarted { get; set; }
        public Nullable<bool> IsRecFinished { get; set; }
        public Nullable<System.DateTime> LecDate { get; set; }
        public Nullable<System.TimeSpan> LecStartingTime { get; set; }
        public Nullable<System.TimeSpan> LecEndingTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string LecCode { get; set; }
    
        public virtual CourseDetail CourseDetail { get; set; }
        public virtual CourseMaterialType CourseMaterialType { get; set; }
    }
}
