//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCoach
    {
        public long CCID { get; set; }
        public Nullable<long> FKCID { get; set; }
        public Nullable<long> FKUID { get; set; }
        public string CTUniversityName { get; set; }
        public string CTName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string PicUrl { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
