//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CoachTaughtBies = new HashSet<CoachTaughtBy>();
            this.CourseCoaches = new HashSet<CourseCoach>();
            this.CourseDetails = new HashSet<CourseDetail>();
            this.CourseLanguages = new HashSet<CourseLanguage>();
            this.Quizs = new HashSet<Quiz>();
            this.UserEnrollCourses = new HashSet<UserEnrollCourse>();
        }
    
        public long CID { get; set; }
        public Nullable<long> CoachID { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<int> TotalDurationDays { get; set; }
        public Nullable<int> TotalQuizes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> FkCCID { get; set; }
        public string CourseSessionID { get; set; }
        public Nullable<int> Pricing { get; set; }
        public Nullable<int> TotalSessions { get; set; }
        public string CourseCode { get; set; }
        public string Commitment { get; set; }
        public string CourseLanguage { get; set; }
        public string LogoUrl { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string HowToPass { get; set; }
        public string LearningLevel { get; set; }
        public Nullable<int> UserRatings { get; set; }
        public string CoachUniversityName { get; set; }
        public Nullable<bool> IsCertificateGiven { get; set; }
        public string BackgroundPicUrl { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string CerticationDescription { get; set; }
        public string CourseImportance { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoachTaughtBy> CoachTaughtBies { get; set; }
        public virtual CourseCategory CourseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCoach> CourseCoaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseDetail> CourseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseLanguage> CourseLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz> Quizs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEnrollCourse> UserEnrollCourses { get; set; }
    }
}
