//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEnrollCourse
    {
        public long UECID { get; set; }
        public Nullable<long> FKUID { get; set; }
        public Nullable<long> FKCID { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CardExpMonth { get; set; }
        public Nullable<int> CardExpYear { get; set; }
        public Nullable<int> FKCNTRYID { get; set; }
        public Nullable<int> CVV { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCertified { get; set; }
        public Nullable<System.DateTime> CertifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
