//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuizAttemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserQuizAttemp()
        {
            this.UserQuizAnswers = new HashSet<UserQuizAnswer>();
        }
    
        public long UQID { get; set; }
        public Nullable<long> FkQZID { get; set; }
        public Nullable<long> FkUID { get; set; }
        public Nullable<int> Marks { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> TotalAttempts { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuizAnswer> UserQuizAnswers { get; set; }
    }
}
