//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFollower
    {
        public long UFID { get; set; }
        public Nullable<long> FkUID { get; set; }
        public Nullable<long> FkFollowerID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsFollowed { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
