//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGivenQuesAn
    {
        public long UQAID { get; set; }
        public Nullable<long> FkUQDID { get; set; }
        public Nullable<long> FkUQID { get; set; }
        public Nullable<long> FkUserID { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsOptionRight { get; set; }
        public Nullable<bool> IsUserRight { get; set; }
        public string OptionName { get; set; }
        public string Question { get; set; }
        public Nullable<long> FkQTID { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserQuestionDetail UserQuestionDetail { get; set; }
        public virtual UserQuestion UserQuestion { get; set; }
    }
}
