//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuizAnswer
    {
        public long UQAID { get; set; }
        public Nullable<long> FkUQID { get; set; }
        public Nullable<long> FkQSID { get; set; }
        public Nullable<long> FkQDID { get; set; }
        public string QAns { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuestionsDetail QuestionsDetail { get; set; }
        public virtual UserQuizAttemp UserQuizAttemp { get; set; }
    }
}
