//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExperience
    {
        public long UEXID { get; set; }
        public Nullable<long> FkUID { get; set; }
        public string CompanyName { get; set; }
        public string UserPost { get; set; }
        public Nullable<int> TotalExperience { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> FromMonth { get; set; }
        public Nullable<int> FromDay { get; set; }
        public Nullable<int> ToYear { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<int> ToDay { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public string Location { get; set; }
        public string CompLogoUrl { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
