//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWill_MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public int YID { get; set; }
        public Nullable<int> Year1 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
